server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
#          uri: http://localhost:8081
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
              - Path=/ratings/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
#              - Path=/hotels/**,/staffs/**
              - Path=/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    enable: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-56546759.okta.com/oauth2/default
    audience: api://default
    client-id: 0oadiv5qmbEAbCeU55d7
    client-secret: YSnjYnM7Xl-ZnVWBD7wipjqDuxoDhofEcx5jkmsDBQ89oTydlEtYfzOmzMWi6qC6
    scopes:
      - openid, profile, email, offline_access